### PR TITLE
Changed reference to copy from front() of _eventQueue

### PR DESCRIPTION
**Pull request by som-dev**
auto& event is a reference to the front of the queue, then the front element is removed (popped), then event member data is used. However, std::deque documentation for pop_front() states "iterators, pointers and references referring to the removed element are invalidated."
Therefore it is possible that the memory underneath event is reclaimed/reused for something else.
Most likely event's data is probably unchanged and the copy will be more expensive, but I feel it is worth fixing.

### CODE REVIEW

**Comment by som-dev** [comment]
I forgot to run the python tests which seems to fail after this change - I'll keep looking into this.

**Comment by som-dev** [comment]
It appears tests/python/test_qryptominer.py::TestQryptominer::test_miner_simple sporadically fails in both master and the branch with this fix so I suspect it is unrelated.

**Comment by jleni** [comment]
It is likely that there are a few nonce that pass the target and we didnt notice that before.
The event is raised for the first thread that finds a solution.
It would be necessary to verify if the solution is valid.

**Comment by som-dev** [comment]
You are correct.
The test expects a nonce of 1:
tests/python/test_qryptominer.py::TestQryptominer::test_miner_simple Hey a solution has been found! 1
input_bytes     [3, 5, 7, 9, 25]
solution_input  [0, 0, 0, 1, 25]
target          [30, 229, 63, 225, 172, 243, 85, 146, 102, 216, 67, 137, 206, 222, 153, 51, 198, 143, 197, 30, 208, 166, 199, 145, 248, 249, 232, 157, 182, 35, 240, 255]
solutionHash    (50, 97, 190, 143, 93, 96, 239, 140, 210, 86, 9, 140, 164, 169, 96, 33, 73, 135, 223, 105, 86, 193, 33, 112, 64, 179, 107, 102, 95, 208, 179, 88)

However, a nonce of 0 also is less than the target:

tests/python/test_qryptominer.py::TestQryptominer::test_miner_simple Hey a solution has been found! 0
input_bytes     [3, 5, 7, 9, 25]
solution_input  [0, 0, 0, 0, 25]
target          [30, 229, 63, 225, 172, 243, 85, 146, 102, 216, 67, 137, 206, 222, 153, 51, 198, 143, 197, 30, 208, 166, 199, 145, 248, 249, 232, 157, 182, 35, 240, 255]
solutionHash    (235, 164, 90, 71, 117, 235, 74, 46, 16, 87, 181, 204, 35, 157, 13, 134, 146, 95, 225, 116, 234, 104, 86, 239, 53, 85, 9, 122, 245, 30, 156, 192)

I can fix this by adjusting the target to something smaller.  However, I am now struggling to understand what the difference would be between test_miner_simple and test_miner_verify.
I guess test_miner_simple was supposed to be a well-known case where only nonce 1 would be the solution?

**Comment by jleni** [comment]
yes, it is basically that. In one case is expecting a fixed value. In the other it issues the verify function, changes the nonce and confirms that verification fails.

**Comment by som-dev** [comment]
I found nonce 6 creates a relatively small number (the last number starts with 0):
raw     Hash    (134, 69, 87, 129, 233, 145, 65, 39, 254, 6, 94, 215, 127, 250, 112, 183, 241, 168, 4, 110, 220, 93, 7, 98, 86, 146, 24, 232, 170, 184, 120, 0)
So I think it should be safe to set the target to slightly higher than this and expect 6 without multiple threads providing solutions.

**Pull request merged**
